"""initial schema

The one migration this repository has: every table from Task 2's models,
generated with `alembic revision --autogenerate` and then read line by line
against `triviador.db.models` before being trusted (see the Task 3 report for
what autogenerate got right and what, if anything, needed a hand fix).

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-16 22:13:58.534064

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_table(
        "rule_presets",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_presets")),
    )
    op.create_index(
        "uq_rule_presets_single_default",
        "rule_presets",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("map_id", sa.Text(), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preset_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("host_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("winner_id", sa.Text(), nullable=True),
        sa.Column("last_seq", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('lobby', 'expansion', 'battle', 'finished', 'aborted')",
            name=op.f("ck_games_status_valid"),
        ),
        sa.ForeignKeyConstraint(["host_id"], ["users.id"], name=op.f("fk_games_host_id_users")),
        sa.ForeignKeyConstraint(
            ["preset_id"], ["rule_presets.id"], name=op.f("fk_games_preset_id_rule_presets")
        ),
        sa.ForeignKeyConstraint(["winner_id"], ["users.id"], name=op.f("fk_games_winner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
    )
    op.create_table(
        "invite_codes",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_by", sa.Text(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_invite_codes_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["used_by"], ["users.id"], name=op.f("fk_invite_codes_used_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invite_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_invite_codes_code_hash")),
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_media_assets_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_table(
        "question_imports",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("uploaded_by", sa.Text(), nullable=False),
        sa.Column("upload_sha256", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column(
            "staged_key",
            sa.Text(),
            nullable=True,
            comment=(
                "Key into the private `triviador-staging` bucket, never the public "
                "`triviador-media` bucket (§9.1). Set NULL once the staged object is "
                "retired (expiry or post-confirm cleanup) — the row remains as an "
                "audit trail. The bucket, not a prefix, is the security boundary: "
                "staged uploads carry unpublished answer keys."
            ),
        ),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_question_imports_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_imports")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_table(
        "game_events",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("operation_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_game_events_game_id_games")
        ),
        sa.PrimaryKeyConstraint("game_id", "seq", name=op.f("pk_game_events")),
    )
    op.create_index(
        "ix_game_events_game_id_operation_id",
        "game_events",
        ["game_id", "operation_id"],
        unique=False,
    )
    op.create_table(
        "game_players",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("seat", sa.Integer(), nullable=False),
        sa.Column("final_score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_game_players_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_game_players_user_id_users")
        ),
        sa.PrimaryKeyConstraint("game_id", "user_id", name=op.f("pk_game_players")),
        sa.UniqueConstraint("game_id", "seat", name=op.f("uq_game_players_game_id")),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("category_id", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.Text(), nullable=False),
        sa.Column("media_asset_id", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("prompt_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "difficulty IN ('easy', 'medium', 'hard')", name=op.f("ck_questions_difficulty_valid")
        ),
        sa.CheckConstraint(
            "kind IN ('multiple_choice', 'numeric')", name=op.f("ck_questions_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_questions_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_questions_media_asset_id_media_assets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    op.create_table(
        "question_choices",
        sa.Column("question_id", sa.Text(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("media_asset_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_question_choices_media_asset_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_choices_question_id_questions"),
        ),
        sa.PrimaryKeyConstraint("question_id", "idx", name=op.f("pk_question_choices")),
    )
    op.create_table(
        "question_numeric",
        sa.Column("question_id", sa.Text(), nullable=False),
        sa.Column("correct_value", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_numeric_question_id_questions"),
        ),
        sa.PrimaryKeyConstraint("question_id", name=op.f("pk_question_numeric")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Deliberately refuses, rather than shipping autogenerate's silent drop-everything stub.

    `game_events` is append-only (no migration may UPDATE or DELETE it), and the only thing a
    `downgrade` of the *first* migration could possibly mean is dropping every table, event log
    included. Autogenerate's stub would do exactly that, silently, the moment someone reaches for
    `alembic downgrade` out of habit after a bad deploy. There is nothing smaller to roll back to
    once 0001 has run, so this has to be a deliberate, manual `DROP SCHEMA`, not something a script
    can invoke by accident. Raising here — rather than a no-op `pass` — also makes `alembic
    downgrade base` fail loudly instead of quietly reporting success while doing nothing.
    """
    raise NotImplementedError(
        "0001_initial has no downgrade: game_events is append-only, and 'downgrade' from the "
        "first migration can only mean dropping the whole schema including the event log. If "
        "that is genuinely what you want, do it explicitly with DROP SCHEMA, not `alembic "
        "downgrade`."
    )
