// Generates one Zod schema per definition in the exported contracts.
//
// Split into three modules on purpose (§7). A single `rest.ts` would pull
// every top-level Zod construction into the player bundle regardless of
// tree-shaking, because schema construction is a side-effecting top-level
// expression. `admin.ts` is absent because there are no admin DTOs yet —
// Plan 7 adds `contracts/admin.schema.json` and this script picks it up
// with no change.
//
// R-22: `json-schema-to-zod` never resolves `$ref` on its own (verified
// against 2.6.0 through 2.8.1 — there is no `$ref` branch in its parser
// dispatcher; unresolved refs silently fall back to `parseDefault`, i.e.
// `z.any()`). Instead we drive its `parserOverride` hook directly: a
// `{"$ref": "#/$defs/Name"}` node is rewritten to a reference to the
// sibling `nameSchema` const rather than inlined or dropped to `z.any()`.
// That only produces valid JS if every referenced const is already
// declared, so each document's `$defs` are emitted in dependency order
// (topological sort, alphabetical tie-break for determinism) rather than
// alphabetical order alone. A cycle would make that impossible — there is
// none in the current contracts, and if one appears later this throws
// instead of silently emitting a use-before-declaration or masking the
// cycle behind `z.any()`/`z.lazy()`.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseSchema } from "json-schema-to-zod";

const here = dirname(fileURLToPath(import.meta.url));
const contracts = resolve(here, "../../contracts");
const out = resolve(here, "../shared/api/generated");

const HEADER = `// GENERATED by \`pnpm codegen\` from ../../../../contracts. Do not edit.
// CI runs \`pnpm codegen:check\`, which fails on any drift.
import { z } from "zod";
`;

const REF_RE = /^#\/\$defs\/(.+)$/;

function camel(name) {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

/**
 * Replaces a `{"$ref": "#/$defs/Name"}` node with a reference to the
 * sibling `nameSchema` const instead of letting the library fall back to
 * `z.any()`. Runs *instead of* the library's normal per-node wrapping (it
 * short-circuits before that), so `.describe(...)`/`.default(...)`/
 * `.readonly()` on the ref node itself — real cases in these contracts,
 * e.g. `your_options: {"$ref": "#/$defs/YourOptions", "default": {...}}`
 * — are reproduced here to match what the library would have appended.
 */
function refOverride(schema) {
  if (!schema || typeof schema !== "object" || typeof schema.$ref !== "string") return undefined;
  const match = schema.$ref.match(REF_RE);
  if (!match) return undefined;
  let parsed = `${camel(match[1])}Schema`;
  if (schema.description) parsed += `.describe(${JSON.stringify(schema.description)})`;
  if (schema.default !== undefined) parsed += `.default(${JSON.stringify(schema.default)})`;
  if (schema.readOnly) parsed += ".readonly()";
  return parsed;
}

/** Every `#/$defs/X` target referenced anywhere inside a def's schema. */
function refsIn(node, defNames, acc = new Set()) {
  if (Array.isArray(node)) {
    for (const item of node) refsIn(item, defNames, acc);
  } else if (node && typeof node === "object") {
    for (const [key, value] of Object.entries(node)) {
      if (key === "$ref" && typeof value === "string") {
        const match = value.match(REF_RE);
        if (match && defNames.has(match[1])) acc.add(match[1]);
      } else {
        refsIn(value, defNames, acc);
      }
    }
  }
  return acc;
}

/**
 * Topological order over one document's `$defs`, so every `nameSchema`
 * referenced by `refOverride` is declared before it is used. Ties within a
 * round are broken alphabetically so the order — and therefore the
 * generated bytes — is stable across runs, which the drift gate depends
 * on. Throws (rather than emitting a broken or papered-over module) if a
 * cycle makes a valid order impossible.
 */
function topoSort(defs, file) {
  const names = new Set(Object.keys(defs));
  const deps = new Map([...names].map((name) => [name, refsIn(defs[name], names)]));
  const emitted = [];
  const remaining = new Set(names);
  while (remaining.size > 0) {
    const ready = [...remaining]
      .filter((name) => [...deps.get(name)].every((dep) => !remaining.has(dep)))
      .sort();
    if (ready.length === 0) {
      throw new Error(
        `${file}: dependency cycle among $defs, cannot emit in declaration order: ` +
          `${findCycle(remaining, deps).join(" -> ")}`,
      );
    }
    for (const name of ready) {
      emitted.push(name);
      remaining.delete(name);
    }
  }
  return emitted;
}

/** A concrete cycle among the still-unemittable defs, for the error message. */
function findCycle(remaining, deps) {
  const stack = [];
  const onStack = new Set();
  function visit(name) {
    if (onStack.has(name)) return [...stack.slice(stack.indexOf(name)), name];
    stack.push(name);
    onStack.add(name);
    for (const dep of deps.get(name)) {
      if (remaining.has(dep)) {
        const cycle = visit(dep);
        if (cycle) return cycle;
      }
    }
    stack.pop();
    onStack.delete(name);
    return null;
  }
  for (const name of remaining) {
    const cycle = visit(name);
    if (cycle) return cycle;
  }
  return [...remaining]; // unreachable if `remaining` truly has no ready node
}

/** Emit every `$def` of one document as its own exported schema + type. */
function emitDocument(file, outFile) {
  const document = JSON.parse(readFileSync(resolve(contracts, file), "utf8"));
  const defs = document.$defs ?? {};
  const order = topoSort(defs, file);
  const body = order
    .map((name) => {
      const schema = parseSchema(defs[name], {
        seen: new Map(),
        path: [],
        parserOverride: refOverride,
        // `package.json` pins `zod: ^3.24.0`. The library defaults to
        // Zod v4 output (e.g. `z.core.$ZodIssue[]`, which does not exist
        // on the classic v3 build we depend on) unless told otherwise.
        zodVersion: 3,
      });
      return `export const ${camel(name)}Schema = ${schema};\nexport type ${name} = z.infer<typeof ${camel(name)}Schema>;`;
    })
    .join("\n\n");
  writeFileSync(resolve(out, outFile), `${HEADER}\n${body}\n`, "utf8");
  console.log(`${outFile}: ${order.length} schemas`);
}

function emitErrors() {
  const { api_error_code, reject_code } = JSON.parse(
    readFileSync(resolve(contracts, "errors.json"), "utf8"),
  );
  const enumOf = (values) => `z.enum([${values.map((v) => JSON.stringify(v)).join(", ")}])`;
  writeFileSync(
    resolve(out, "errors.ts"),
    `${HEADER}
export const apiErrorCodeSchema = ${enumOf(api_error_code)};
export type ApiErrorCode = z.infer<typeof apiErrorCodeSchema>;

export const rejectCodeSchema = ${enumOf(reject_code)};
export type RejectCode = z.infer<typeof rejectCodeSchema>;

// One closed union, as the envelope declares it. The two value sets are
// disjoint — the backend asserts that — so this discriminates cleanly.
export const errorCodeSchema = z.union([apiErrorCodeSchema, rejectCodeSchema]);
export type ErrorCode = z.infer<typeof errorCodeSchema>;
`,
    "utf8",
  );
  console.log(`errors.ts: ${api_error_code.length + reject_code.length} codes`);
}

mkdirSync(out, { recursive: true });
emitDocument("rest.schema.json", "public.ts");
emitDocument("ws.schema.json", "ws.ts");
emitErrors();
