/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as AuthedRouteImport } from './_authed'
import { Route as LoginRouteImport } from './login'
import { Route as RedeemRouteImport } from './redeem'
import { Route as AuthedIndexRouteImport } from './_authed.index'
import { Route as AuthedAdminRouteImport } from './_authed.admin'
import { Route as AuthedAdminIndexRouteImport } from './_authed.admin.index'
import { Route as AuthedGamesGameIdRouteImport } from './_authed.games.$gameId'
import { Route as AuthedAdminQuestionsIndexRouteImport } from './_authed.admin.questions.index'
import { Route as AuthedAdminQuestionsQuestionIdRouteImport } from './_authed.admin.questions.$questionId'
import { Route as AuthedAdminQuestionsImportRouteImport } from './_authed.admin.questions.import'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import('./_authed.admin.lazy').then((d) => d.Route))
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedGamesGameIdRoute = AuthedGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminQuestionsIndexRoute =
  AuthedAdminQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./_authed.admin.questions.index.lazy').then((d) => d.Route),
  )
const AuthedAdminQuestionsQuestionIdRoute =
  AuthedAdminQuestionsQuestionIdRouteImport.update({
    id: '/questions/$questionId',
    path: '/questions/$questionId',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./_authed.admin.questions.$questionId.lazy').then((d) => d.Route),
  )
const AuthedAdminQuestionsImportRoute =
  AuthedAdminQuestionsImportRouteImport.update({
    id: '/questions/import',
    path: '/questions/import',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./_authed.admin.questions.import.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/redeem': typeof RedeemRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/games/$gameId': typeof AuthedGamesGameIdRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/admin/questions/$questionId': typeof AuthedAdminQuestionsQuestionIdRoute
  '/admin/questions/import': typeof AuthedAdminQuestionsImportRoute
  '/admin/questions/': typeof AuthedAdminQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/redeem': typeof RedeemRoute
  '/': typeof AuthedIndexRoute
  '/games/$gameId': typeof AuthedGamesGameIdRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/questions/$questionId': typeof AuthedAdminQuestionsQuestionIdRoute
  '/admin/questions/import': typeof AuthedAdminQuestionsImportRoute
  '/admin/questions': typeof AuthedAdminQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/redeem': typeof RedeemRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/games/$gameId': typeof AuthedGamesGameIdRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/admin/questions/$questionId': typeof AuthedAdminQuestionsQuestionIdRoute
  '/_authed/admin/questions/import': typeof AuthedAdminQuestionsImportRoute
  '/_authed/admin/questions/': typeof AuthedAdminQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/redeem'
    | '/admin'
    | '/games/$gameId'
    | '/admin/'
    | '/admin/questions/$questionId'
    | '/admin/questions/import'
    | '/admin/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/redeem'
    | '/'
    | '/games/$gameId'
    | '/admin'
    | '/admin/questions/$questionId'
    | '/admin/questions/import'
    | '/admin/questions'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/redeem'
    | '/_authed/admin'
    | '/_authed/'
    | '/_authed/games/$gameId'
    | '/_authed/admin/'
    | '/_authed/admin/questions/$questionId'
    | '/_authed/admin/questions/import'
    | '/_authed/admin/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RedeemRoute: typeof RedeemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/games/$gameId': {
      id: '/_authed/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthedGamesGameIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/questions/': {
      id: '/_authed/admin/questions/'
      path: '/questions'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AuthedAdminQuestionsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/questions/$questionId': {
      id: '/_authed/admin/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/admin/questions/$questionId'
      preLoaderRoute: typeof AuthedAdminQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/questions/import': {
      id: '/_authed/admin/questions/import'
      path: '/questions/import'
      fullPath: '/admin/questions/import'
      preLoaderRoute: typeof AuthedAdminQuestionsImportRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminQuestionsQuestionIdRoute: typeof AuthedAdminQuestionsQuestionIdRoute
  AuthedAdminQuestionsImportRoute: typeof AuthedAdminQuestionsImportRoute
  AuthedAdminQuestionsIndexRoute: typeof AuthedAdminQuestionsIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminQuestionsQuestionIdRoute: AuthedAdminQuestionsQuestionIdRoute,
  AuthedAdminQuestionsImportRoute: AuthedAdminQuestionsImportRoute,
  AuthedAdminQuestionsIndexRoute: AuthedAdminQuestionsIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedGamesGameIdRoute: typeof AuthedGamesGameIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedGamesGameIdRoute: AuthedGamesGameIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RedeemRoute: RedeemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
